// File: src/app/terms/page.tsx
import React from 'react';
import Link from 'next/link';
import { ArrowLeft, FileText } from 'lucide-react';

export const metadata = {
  title: 'Terms of Service | Seloice Tools',
  description: 'Terms and conditions for using Seloice Tools.',
};

export default function TermsOfService() {
  return (
    <div className="min-h-screen bg-[#050505] text-gray-300 font-sans selection:bg-indigo-500/30">
      <div className="max-w-4xl mx-auto px-6 py-20">
        <Link href="/" className="inline-flex items-center gap-2 text-indigo-500 hover:text-indigo-400 font-bold text-sm uppercase tracking-widest mb-12 transition-colors">
          <ArrowLeft size={16} /> Back to Home
        </Link>
        
        <div className="flex items-center gap-4 mb-8">
          <div className="w-12 h-12 rounded-2xl bg-indigo-500/10 border border-indigo-500/20 flex items-center justify-center text-indigo-500">
            <FileText size={24} />
          </div>
          <h1 className="text-4xl md:text-5xl font-black italic tracking-tight text-white">Terms of Service</h1>
        </div>
        
        <p className="text-sm font-bold uppercase tracking-widest text-gray-500 mb-12 border-b border-white/10 pb-6">Last Updated: May 2026</p>

        <div className="space-y-8 text-sm md:text-base leading-relaxed">
          <section>
            <h2 className="text-2xl font-black text-white mb-4">1. Acceptance of Terms</h2>
            <p className="text-gray-400">By accessing and using Seloice Tools (the "Service"), you accept and agree to be bound by the terms and provision of this agreement. If you do not agree to abide by these terms, please do not use this service. Your continued use of the site constitutes your acceptance of any updates or modifications to these Terms.</p>
          </section>

          <section>
            <h2 className="text-2xl font-black text-white mb-4">2. Description of Service</h2>
            <p className="text-gray-400">Seloice Tools provides a suite of online utilities for content creators, including but not limited to video editors, downloaders, AI text generators, image editors, and audio tools. These tools are provided "as is" and we reserve the right to modify, suspend, or discontinue any tool at our discretion without prior notice.</p>
          </section>

          <section>
            <h2 className="text-2xl font-black text-white mb-4">3. Use of Downloader Tools & Fair Use</h2>
            <p className="text-gray-400">Our media downloading tools are intended strictly for downloading your own content, content in the public domain, or content for which you have explicit permission from the copyright holder. You agree NOT to use our tools to download copyrighted material for unauthorized distribution, commercial use, or piracy. You bear sole responsibility for your use of these downloading utilities.</p>
          </section>

          <section>
            <h2 className="text-2xl font-black text-white mb-4">4. User Privacy and Local Processing</h2>
            <p className="text-gray-400">Many of our tools run locally in your web browser (client-side), meaning your files are not uploaded to our servers. However, some tools (like AI text generation) require server processing. By using these tools, you consent to the processing of your inputs. Please review our <Link href="/privacy" className="text-indigo-400 hover:underline">Privacy Policy</Link> for detailed information on data handling.</p>
          </section>

          <section>
            <h2 className="text-2xl font-black text-white mb-4">5. Intellectual Property Rights (Seloice Tools)</h2>
            <p className="text-gray-400">The Service and its original content, features, functionality, source code, and design are owned by Seloice Tools and are protected by international copyright, trademark, patent, trade secret, and other intellectual property or proprietary rights laws. You may not copy, reverse engineer, or redistribute our tools without written permission.</p>
          </section>

          <section>
            <h2 className="text-2xl font-black text-white mb-4">6. Third-Party Content and Output</h2>
            <p className="text-gray-400">Content generated by our AI tools may resemble existing works due to the nature of machine learning. We do not claim ownership of the output you generate, nor do we guarantee that the output does not infringe on third-party rights. You are responsible for reviewing and verifying the legality of using generated content in your own projects.</p>
          </section>

          <section>
            <h2 className="text-2xl font-black text-white mb-4">7. Advertising and Monetization</h2>
            <p className="text-gray-400">Seloice Tools is provided for free and is supported by advertising networks, including Google AdSense. We may display personalized or non-personalized advertisements based on your consent and location. We do not endorse the products or services advertised, and your interactions with advertisers are solely between you and the advertiser.</p>
          </section>

          <section>
            <h2 className="text-2xl font-black text-white mb-4">8. Prohibited Activities</h2>
            <p className="text-gray-400 mb-2">You agree not to engage in any of the following activities:</p>
            <ul className="list-disc list-inside text-gray-400 space-y-1 ml-4">
              <li>Using the tools to generate illegal, hateful, or abusive content.</li>
              <li>Attempting to bypass our rate limits, API protections, or security measures.</li>
              <li>Using automated scripts, bots, or scrapers to access the Service.</li>
              <li>Overloading our servers with excessive requests.</li>
              <li>Using the service for commercial mass-scraping or redistribution.</li>
            </ul>
          </section>

          <section>
            <h2 className="text-2xl font-black text-white mb-4">9. Disclaimer of Warranties</h2>
            <p className="text-gray-400">Seloice Tools is provided "as is" and "as available" without any representations or warranties, express or implied. We do not warrant that the website will be constantly available, secure, free of errors or viruses, or that the tools will perfectly process every single file type without issues.</p>
          </section>

          <section>
            <h2 className="text-2xl font-black text-white mb-4">10. Limitations of Liability</h2>
            <p className="text-gray-400">In no event shall Seloice Tools, nor its directors, employees, partners, agents, or affiliates, be liable for any indirect, incidental, special, consequential or punitive damages, including without limitation, loss of profits, data, use, goodwill, or other intangible losses, resulting from your access to or use of or inability to access or use the Service.</p>
          </section>

          <section>
            <h2 className="text-2xl font-black text-white mb-4">11. Indemnification</h2>
            <p className="text-gray-400">You agree to defend, indemnify and hold harmless Seloice Tools and its licensee and licensors, and their employees, contractors, agents, officers and directors, from and against any and all claims, damages, obligations, losses, liabilities, costs or debt, and expenses resulting from your use and access of the Service, or a breach of these Terms.</p>
          </section>

          <section>
            <h2 className="text-2xl font-black text-white mb-4">12. Modifications to the Service</h2>
            <p className="text-gray-400">We reserve the right at any time to modify or discontinue, temporarily or permanently, the Service (or any part thereof) with or without notice. We shall not be liable to you or to any third party for any modification, suspension or discontinuance of the Service.</p>
          </section>
          
          <section>
            <h2 className="text-2xl font-black text-white mb-4">13. Governing Law and Jurisdiction</h2>
            <p className="text-gray-400">These Terms shall be governed and construed in accordance with the laws of India, specifically within the jurisdiction of Bihar, without regard to its conflict of law provisions. Our failure to enforce any right or provision of these Terms will not be considered a waiver of those rights.</p>
          </section>

          <section>
            <h2 className="text-2xl font-black text-white mb-4">14. Contact Information</h2>
            <p className="text-gray-400">If you have any questions about these Terms of Service, please contact us at <a href="mailto:hello@seloice.com" className="text-indigo-400 hover:underline">hello@seloice.com</a>.</p>
          </section>
        </div>
      </div>
    </div>
  );
}